- name: ContainerD Installation
  hosts: localhost
  become: true
  gather_facts: true

  vars_files:
    - defaults/main.yaml

  tasks:
    - name: All
      ansible.builtin.include_tasks: "tasks/main.yaml"
