- name: Create the working directory for temporary installation artifacts
  ansible.builtin.file:
    path: "{{ temporary_folder }}"
    state: directory
    mode: "0750"

- name: Create the temporary containerd extraction directory
  ansible.builtin.file:
    path: "{{ temporary_folder }}/containerd"
    state: directory
    mode: "0750"

- name: Create the temporary CNI plugin extraction directory
  ansible.builtin.file:
    path: "{{ temporary_folder }}/cni"
    state: directory
    mode: "0750"

- name: Create the systemd unit directory for containerd
  ansible.builtin.file:
    path: "{{ containerd_systemctl_folder }}"
    state: directory
    mode: "0750"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Create the final CNI plugin installation directory
  ansible.builtin.file:
    path: "{{ cni_plugin_folder }}"
    state: directory
    mode: "0750"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
