- name: Download the containerd archive
  ansible.builtin.get_url:
    url: "{{ containerd_url }}"
    dest: "{{ temporary_folder }}/containerd.tar.gz"
    mode: "0644"
    force: false
    validate_certs: true
    timeout: 60

- name: Download the runc binary
  ansible.builtin.get_url:
    url: "{{ runc_url }}"
    dest: "{{ temporary_folder }}/runc"
    mode: "0644"
    force: false
    validate_certs: true
    timeout: 60

- name: Download the CNI plugin archive
  ansible.builtin.get_url:
    url: "{{ cni_plugin_url }}"
    dest: "{{ temporary_folder }}/cni.tgz"
    mode: "0644"
    force: false
    validate_certs: true
    timeout: 60

- name: Download the containerd systemd service unit
  ansible.builtin.get_url:
    url: "{{ containerd_systemctl_url }}"
    dest: "{{ temporary_folder }}/containerd.service"
    mode: "0644"
    force: false
    validate_certs: true
    timeout: 60
