- name: Copy containerD binaries
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/containerd/bin/"
    dest: "{{ install_path }}"
    remote_src: true
    mode: "0755"

- name: Copy containerd systemd service file
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/containerd.service"
    dest: "{{ containerd_systemctl_folder }}/containerd.service"
    remote_src: true
    mode: "0644"

- name: Copy runc binary
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/runc"
    dest: "{{ runc_path }}"
    remote_src: true
    mode: "0755"

- name: Copy CNI plugin binaries
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/cni/"
    dest: "{{ cni_plugin_folder }}"
    remote_src: true
    mode: "0755"
