temporary_folder: "/tmp/ansible-containerd"

install_path: /usr/local/bin

containerd_version: "1.7.28"
containerd_url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
containerd_systemctl_url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
containerd_systemctl_folder: "/usr/local/lib/systemd/system/"

runc_version: "1.3.0"
runc_url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
runc_path: "/usr/local/sbin/runc"

cni_plugin_version: "1.7.1"
cni_plugin_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugin_version }}/cni-plugins-linux-amd64-v{{ cni_plugin_version }}.tgz"
cni_plugin_folder: "/opt/cni/bin"
