- name: Copy Files
  block:
    - name: Copy containerD binaries
      ansible.builtin.copy:
        src: "{{ temporary_folder }}/containerd/bin/"
        dest: "{{ install_path }}"
        remote_src: true
        mode: "0755"

    - name: Create SystemD folder
      ansible.builtin.file:
        path: "{{ containerd_systemctl_folder }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    - name: Copy containerd systemd service file
      ansible.builtin.copy:
        src: "{{ temporary_folder }}/containerd.service"
        dest: "{{ containerd_systemctl_folder }}/containerd.service"
        remote_src: true
        mode: "0644"

    - name: Copy runc binary
      ansible.builtin.copy:
        src: "{{ temporary_folder }}/runc"
        dest: "{{ runc_path }}"
        remote_src: true
        mode: "0755"

    - name: Create CNI Folder
      ansible.builtin.file:
        path: "{{ cni_plugin_folder }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    - name: Copy CNI plugin binaries
      ansible.builtin.copy:
        src: "{{ temporary_folder }}/cni/"
        dest: "{{ cni_plugin_folder }}"
        remote_src: true
        mode: "0755"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start containerd service
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true
